- defaults:
    link:
      relink: true

- clean: ["~"]

- create:
    - ~/.bin

- link:
    ~/.bin/tat: bin/tat
    ~/.config/kitty: config/kitty
    ~/.config/nvim: config/nvim
    ~/.curlrc: curlrc
    ~/.gitattributes: gitattributes
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.gitshrc: gitshrc
    ~/.tmux.conf: tmux.conf
    ~/.vimrc: vimrc
    ~/.zshrc: zshrc
