#!/usr/bin/env ruby

# Pretty much an exact copy of
# https://github.com/codegangsta/dotfiles/blob/master/bootstrap

require "fileutils"

def link(path, link_name)
  path = File.expand_path path
  link_name = File.expand_path link_name

  puts "linking #{link_name}..."

  if File.symlink? link_name
    puts "\tRemoving symlink..."
    FileUtils.rm link_name
  elsif File.exists? link_name
    puts "\tSkipping because a file already exists."
    return
  end

  FileUtils.ln_s(path, link_name)
end

puts "Bootstrapping dotfiles..."
link "~/dotfiles/curlrc", "~/.curlrc"
link "~/dotfiles/gitattributes", "~/.gitattributes"
link "~/dotfiles/gitconfig", "~/.gitconfig"
link "~/dotfiles/gitignore_global", "~/.gitignore_global"
link "~/dotfiles/gitshrc", "~/.gitshrc"
link "~/dotfiles/tmux.conf", "~/.tmux.conf"
link "~/dotfiles/vimrc", "~/.vimrc"

# directories
# link "~/dotfiles/vim", "~/.vim"

puts "done"
